spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 380041877780-mms822vuu3vq91s7esun7a9of9tr8l95.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
  profiles:
    active: prod
  output:
    ansi:
      enabled: always
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate:
        default_schema: public
    open-in-view: false
    show-sql: true
