spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 380041877780-mms822vuu3vq91s7esun7a9of9tr8l95.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/flashcards
    username: postgres
    password: 1/Popokatepetl
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
logging:
  config: src/main/resources/log4j2.properties
