spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/flashcards  # Mac 5433, Windows 5432
    username: postgres
    password: 1/Popokatepetl  # vzdy nutno zmenit kvuli gitu
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
logging:
  config: src/main/resources/log4j2.properties

